// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rundfrage.Api.Data;

#nullable disable

namespace Rundfrage.Api.Data.Migrations
{
    [DbContext(typeof(RundfrageDbContext))]
    [Migration("20260913105608_WishLists")]
    partial class WishLists
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Rundfrage.Api.Data.Entities.CandidateDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PollId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PollId", "Date")
                        .IsUnique();

                    b.ToTable("CandidateDays");
                });

            modelBuilder.Entity("Rundfrage.Api.Data.Entities.DayAnswer", b =>
                {
                    b.Property<Guid>("ResponseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CandidateDayId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Availability")
                        .HasColumnType("INTEGER");

                    b.HasKey("ResponseId", "CandidateDayId");

                    b.HasIndex("CandidateDayId");

                    b.ToTable("DayAnswers");
                });

            modelBuilder.Entity("Rundfrage.Api.Data.Entities.Poll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParticipantToken")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RetentionDeadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantToken")
                        .IsUnique();

                    b.HasIndex("RetentionDeadline");

                    b.ToTable("Polls");
                });

            modelBuilder.Entity("Rundfrage.Api.Data.Entities.PollResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EditToken")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PollId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EditToken")
                        .IsUnique();

                    b.HasIndex("PollId");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("Rundfrage.Api.Data.Entities.WishClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimToken")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WishItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClaimToken");

                    b.HasIndex("WishItemId");

                    b.ToTable("WishClaims");
                });

            modelBuilder.Entity("Rundfrage.Api.Data.Entities.WishItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WantedCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WishListId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WishListId", "Name")
                        .IsUnique();

                    b.ToTable("WishItems");
                });

            modelBuilder.Entity("Rundfrage.Api.Data.Entities.WishList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ListToken")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("TargetDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ListToken")
                        .IsUnique();

                    b.HasIndex("TargetDate");

                    b.ToTable("WishLists");
                });

            modelBuilder.Entity("Rundfrage.Api.Data.Entities.CandidateDay", b =>
                {
                    b.HasOne("Rundfrage.Api.Data.Entities.Poll", "Poll")
                        .WithMany("Days")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("Rundfrage.Api.Data.Entities.DayAnswer", b =>
                {
                    b.HasOne("Rundfrage.Api.Data.Entities.CandidateDay", "CandidateDay")
                        .WithMany("Answers")
                        .HasForeignKey("CandidateDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rundfrage.Api.Data.Entities.PollResponse", "Response")
                        .WithMany("Answers")
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateDay");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("Rundfrage.Api.Data.Entities.PollResponse", b =>
                {
                    b.HasOne("Rundfrage.Api.Data.Entities.Poll", "Poll")
                        .WithMany("Responses")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("Rundfrage.Api.Data.Entities.WishClaim", b =>
                {
                    b.HasOne("Rundfrage.Api.Data.Entities.WishItem", "WishItem")
                        .WithMany("Claims")
                        .HasForeignKey("WishItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WishItem");
                });

            modelBuilder.Entity("Rundfrage.Api.Data.Entities.WishItem", b =>
                {
                    b.HasOne("Rundfrage.Api.Data.Entities.WishList", "WishList")
                        .WithMany("Items")
                        .HasForeignKey("WishListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WishList");
                });

            modelBuilder.Entity("Rundfrage.Api.Data.Entities.CandidateDay", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Rundfrage.Api.Data.Entities.Poll", b =>
                {
                    b.Navigation("Days");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("Rundfrage.Api.Data.Entities.PollResponse", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Rundfrage.Api.Data.Entities.WishItem", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("Rundfrage.Api.Data.Entities.WishList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
